### ISSUE TITLE
Subir imágenes de Mockup/Wireframe para desktop y móvil

### ISSUE THREAD

**Issue by ghost** [UCC-LabCompu2/proyecto2023-Fagiano#3]
Recuerda exportar en algún formato de tipo png, jpg o PDF los mockup o wireframe que hayas hehco con alguna herramienta de tipo figma, adobe XD, draw io, Pencil Project, Mockups, Ninja Mock o cualquiera similar

**Comment by edme88** [comment]
Falta Wireframe para dispositivo móvil.
