### ISSUE TITLE
La etiqueta del footer debe estar dentro del body

### ISSUE THREAD

**Issue by ghost** [UCC-LabCompu2/proyecto2023-Fagiano#7]
El body de una págin debe contener todos los elementos visuales que verá el usuario, por lo tanto, el footer debe estar dentro del body.
https://github.com/UCC-LabCompu2/proyecto2023-Fagiano/blob/afb5da350fcccfa93ef56dcbf81c80812c6d54c7/index.html#L102-L105

**Comment by MarcosFagiano** [comment]
en el footer es necesario que muestre algo? o solamente tiene que estar?
